ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS image_crop_x NUMERIC(5,2) NOT NULL DEFAULT 0;

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS image_crop_y NUMERIC(5,2) NOT NULL DEFAULT 0;

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS image_crop_width NUMERIC(5,2) NOT NULL DEFAULT 100;

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS image_crop_height NUMERIC(5,2) NOT NULL DEFAULT 100;

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS image_zoom NUMERIC(4,2) NOT NULL DEFAULT 1.00;

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS headline VARCHAR(255);

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS sub_headline VARCHAR(500);

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS primary_cta_text VARCHAR(120);

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS primary_cta_link VARCHAR(500);

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS secondary_cta_text VARCHAR(120);

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS secondary_cta_link VARCHAR(500);

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS target_link VARCHAR(500);

ALTER TABLE banner_image
ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
